name: Ok To Test

on:
  issue_comment:
    types: [created]
  pull_request:
  repository_dispatch:
    types: [ok-to-test-command]    

jobs:
  ok-to-test:
    runs-on: ubuntu-latest
    steps:
    - name: ok-to-test setup
      uses: eduardoboucas/ok-to-test-action@main
      with:
        appId: ${{ secrets.APP_ID }}
        appPrivateKey: ${{ secrets.PRIVATE_KEY }}
        
    - name: Run tests
      run: npm test
      
    - name: ok-to-test teardown
      uses: eduardoboucas/ok-to-test-action@v0
      with:
        finished: true
